#ifndef ENABLE_GPL
#define ENABLE_GPL 0
#endif

#define CONFIG_POSTPROC 0
#define CONFIG_LIBSMBCLIENT_PROTOCOL 0
#define CONFIG_BLACKFRAME_FILTER 0
#define CONFIG_BOXBLUR_FILTER 0
#define CONFIG_COLORMATRIX_FILTER 0
#define CONFIG_CROPDETECT_FILTER 0
#define CONFIG_DELOGO_FILTER 0
#define CONFIG_EBUR128_FILTER 0
#define CONFIG_EQ_FILTER 0
#define CONFIG_FSPP_FILTER 0
#define CONFIG_GEQ_FILTER 0
#define CONFIG_HISTEQ_FILTER 0
#define CONFIG_HQDN3D_FILTER 0
#define CONFIG_INTERLACE_FILTER 0
#define CONFIG_KERNDEINT_FILTER 0
#define CONFIG_MCDEINT_FILTER 0
#define CONFIG_MPDECIMATE_FILTER 0
#define CONFIG_MPTESTSRC_FILTER 0
#define CONFIG_PERSPECTIVE_FILTER 0
#define CONFIG_PP7_FILTER 0
#define CONFIG_OWDENOISE_FILTER 0
#define CONFIG_PHASE_FILTER 0
#define CONFIG_PP_FILTER 0
#define CONFIG_PULLUP_FILTER 0
#define CONFIG_REPEATFIELDS_FILTER 0
#define CONFIG_SAB_FILTER 0
#define CONFIG_SMARTBLUR_FILTER 0
#define CONFIG_SPP_FILTER 0
#define CONFIG_STEREO3D_FILTER 0
#define CONFIG_SUPER2XSAI_FILTER 0
#define CONFIG_TINTERLACE_FILTER 0
#define CONFIG_USPP_FILTER 0
#define CONFIG_FREI0R 0

#define CONFIG_LIBCDIO 0
#define CONFIG_LIBCDIO_INDEV 0

#define CONFIG_LIBUTVIDEO 0
#define CONFIG_LIBUTVIDEO_DECODER 0
#define CONFIG_LIBUTVIDEO_ENCODER 0

#define CONFIG_LIBVIDSTAB 0


#define CONFIG_LIBX264 ENABLE_GPL
#define CONFIG_LIBX264_ENCODER ENABLE_GPL
#define CONFIG_LIBX264RGB_ENCODER ENABLE_GPL
#define CONFIG_LIBX265_ENCODER 0

#define CONFIG_LIBX265 0

#define CONFIG_LIBXAVS 0
#define CONFIG_LIBXAVS_ENCODER 0

#define CONFIG_LIBXVID 0
#define CONFIG_LIBXVID_ENCODER 0

#define CONFIG_LIBZVBI 0
#define CONFIG_LIBZVBI_TELETEXT_DECODER 0

#define CONFIG_X11GRAB 0
#define CONFIG_X11GRAB_INDEV 0
#define CONFIG_X11GRAB_XCB_INDEV 0


#define CONFIG_LIBOPENCORE_AMRNB_ENCODER 0
#define CONFIG_LIBOPENCORE_AMRNB 0
#define CONFIG_LIBOPENCORE_AMRWB 0
#define CONFIG_LIBOPENCORE_AMRNB_DECODER 0
#define CONFIG_LIBOPENCORE_AMRWB_DECODER 0

#define CONFIG_LIBVO_AACENC 0
#define CONFIG_LIBVO_AACENC_ENCODER 0
#define CONFIG_LIBVO_AMRWBENC 0
#define CONFIG_LIBVO_AMRWBENC_ENCODER 0







