#ifdef ENABLE_NONFREE
#define ENABLE_NONFREE 0
#endif

#define CONFIG_LIBAACPLUS 0
#define CONFIG_LIBAACPLUS_ENCODER 0

#define CONFIG_LIBFAAC 0
#define CONFIG_LIBFAAC_ENCODER 0

#define CONFIG_NVENC_ENCODER 0

#define CONFIG_LIBFDK_AAC 0
#define CONFIG_LIBFDK_AAC_DECODER 0
#define CONFIG_LIBFDK_AAC_ENCODER 0

#define CONFIG_OPENSSL 0

